import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)('/Users/funakoshiakira/workspace/mirror-app/node_modules/@playwright/test');
const base=process.env.QA_BASE_URL||'http://127.0.0.1:5295',out=`docs/dynamic-simulation/evidence/loading/${process.env.QA_RUN||'local'}`;await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const report={base,checks:[],errors:[]};const assert=(v,m)=>{if(!v)throw Error(m)};async function check(name,fn){try{report.checks.push({name,pass:true,detail:await fn()})}catch(e){report.checks.push({name,pass:false,error:String(e)})}}
async function page(mobile=false){const p=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile});p.on('pageerror',e=>report.errors.push(String(e)));return p}async function boot(p){await p.goto(base);await p.waitForFunction(()=>window.app?.simulation)}
try{
 const p=await page();let release;const gate=new Promise(r=>release=r);await p.route('**/simulation/terrain.json',async r=>{await gate;await r.continue()});await boot(p);
 await check('map pin button opens placement and loading during terrain fetch',async()=>{await p.locator('#simulationMapPick').click();await p.waitForTimeout(900);assert(await p.locator('#simulationLoading').isVisible(),'no loading');assert(await p.locator('#simulationPick').innerText()==='📍 ピンを立てる','unclear pin label');assert(await p.locator('#simulationMapPick').getAttribute('aria-pressed')==='true','not placing');await p.screenshot({path:out+'/loading-desktop.png'});return p.locator('#simulationLoadingDetail').innerText()});
 await check('cancel while terrain pending removes loading and stale results',async()=>{await p.locator('#simulationMapCancel').click();assert(await p.locator('#simulationLoading').isHidden(),'loading remains');release();await p.waitForTimeout(1000);assert(await p.evaluate(()=>!window.app.simulation.result),'cancelled result returned')});
 await p.unroute('**/simulation/terrain.json');
 await check('retry completes and dismisses spinner',async()=>{await p.locator('#simulationRun').click();await p.waitForFunction(()=>!!window.app.simulation.result);assert(await p.locator('#simulationLoading').isHidden(),'finished loading visible');return p.locator('#simulationStatus').innerText()});
 await check('actual worker progress shown and mode exit cancels loading',async()=>{await p.locator('#simulationDuration').fill('120');await p.locator('#simulationDuration').dispatchEvent('input');await p.waitForFunction(()=>Number(document.querySelector('#simulationMapProgress').value)>0&&window.app.simulation.running);assert(await p.locator('#simulationLoading').isVisible(),'worker no loading');await p.screenshot({path:out+'/worker-progress.png'});await p.locator('#simulationModeOfficial').check();assert(await p.locator('#simulationLoading').isHidden(),'mode exit loading remains');await p.waitForTimeout(700);assert(await p.evaluate(()=>!window.app.simulation.result),'stale after exit')});
 const f=await page();await f.route('**/simulation/terrain.json',r=>r.fulfill({status:503,body:'QA outage'}));await boot(f);await check('fetch error dismisses spinner and gives error',async()=>{await f.locator('#simulationMapPick').click();await f.waitForFunction(()=>document.querySelector('#simulationStatus').textContent.includes('計算できません'));assert(await f.locator('#simulationLoading').isHidden(),'failed loading remains');return f.locator('#simulationStatus').innerText()});
 const m=await page(true);let mobileRelease;const mobileGate=new Promise(r=>mobileRelease=r);await m.route('**/simulation/terrain.json',async r=>{await mobileGate;await r.continue()});await boot(m);await check('mobile map button and loading are visible without scrolling',async()=>{await m.locator('#simulationMapPick').tap();await m.waitForTimeout(800);const b=await m.locator('#simulationLoading').boundingBox(),panel=await m.locator('#panelToggle').boundingBox();assert(b&&b.y+b.height<=panel.y,'loading obscured by mobile panel');assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow');await m.screenshot({path:out+'/loading-mobile.png'});await m.locator('#simulationMapCancel').tap();assert(await m.locator('#simulationLoading').isHidden(),'mobile cancel failed');return b});mobileRelease();await m.waitForTimeout(200);
}finally{await browser.close();await writeFile(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.errors.length||report.checks.some(c=>!c.pass))process.exitCode=1}
